### ISSUE TITLE
Validate Custom Tags

### ISSUE THREAD

**Issue by ddkasa** [RodrigoGonzalez/check-mkdocs#30]
So I am using the pre-commit hook to validate my mkdocs configuration and build.

When adding this to much my configuration I get this traceback: 

```bash
check-mkdocs.............................................................Failed
- hook id: check-mkdocs
- exit code: 1

'tag:yaml.org,2002:python/name:mermaid2.fence_mermaid_custom'
  in "mkdocs.yml", line 99, column 19

    Traceback (most recent call last):
      File "/home/dk/.cache/pre-commit/repospe1nroe/py_env-python3/lib/python3.12/site-packages/check_mkdocs/check_mkdocs.py", line 120, in main
        config = yaml.safe_load(f)
                 ^^^^^^^^^^^^^^^^^
      File "/home/dk/.cache/pre-commit/repospe1nroe/py_env-python3/lib64/python3.12/site-packages/yaml/__init__.py", line 125, in safe_load
        return load(stream, SafeLoader)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dk/.cache/pre-commit/repospe1nroe/py_env-python3/lib64/python3.12/site-packages/yaml/__init__.py", line 81, in load
        return loader.get_single_data()
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dk/.cache/pre-commit/repospe1nroe/py_env-python3/lib64/python3.12/site-packages/yaml/constructor.py", line 51, in get_single_data
        return self.construct_document(node)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dk/.cache/pre-commit/repospe1nroe/py_env-python3/lib64/python3.12/site-packages/yaml/constructor.py", line 60, in construct_document
        for dummy in generator:
                     ^^^^^^^^^
      File "/home/dk/.cache/pre-commit/repospe1nroe/py_env-python3/lib64/python3.12/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
        value = self.construct_mapping(node)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dk/.cache/pre-commit/repospe1nroe/py_env-python3/lib64/python3.12/site-packages/yaml/constructor.py", line 218, in construct_mapping
        return super().construct_mapping(node, deep=deep)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dk/.cache/pre-commit/repospe1nroe/py_env-python3/lib64/python3.12/site-packages/yaml/constructor.py", line 143, in construct_mapping
        value = self.construct_object(value_node, deep=deep)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dk/.cache/pre-commit/repospe1nroe/py_env-python3/lib64/python3.12/site-packages/yaml/constructor.py", line 100, in construct_object
        data = constructor(self, node)
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dk/.cache/pre-commit/repospe1nroe/py_env-python3/lib64/python3.12/site-packages/yaml/constructor.py", line 427, in construct_undefined
        raise ConstructorError(None, None,
    yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/name:mermaid2.fence_mermaid_custom'
      in "mkdocs.yml", line 99, column 19
```

This is my pre-commit configuration:

```yaml
  - repo: https://github.com/RodrigoGonzalez/check-mkdocs
    rev: v1.2.0
    hooks:
      - id: check-mkdocs
        name: check-mkdocs
        args: ["--config", "mkdocs.yml"]
        additional_dependencies:
          [
            "mkdocs-material",
            "mkdocs-callouts",
            "pymdown-extensions",
            "markdown",
            "markdown-callouts",
            "mdx-gh-links",
            "mkdocs-click",
            "mkdocs-redirects",
            "mkdocs-autorefs",
            "mkdocs-literate-nav",
            "mkdocstrings[python]",
            "mkdocs-simple-hooks",
            "mkdocs-glightbox",
            "mkdocs-mermaid2-plugin",
            "mkdocs-macros-plugin",
            "pygments",
            "mkdocs-panzoom-plugin",
          ]
```

So I have tracked it down to being an issue with **pyyaml** not parsing custom tags correctly, as I am using custom fences with **pymdownx**
```yaml
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
```

This [issue](https://github.com/yaml/pyyaml/issues/86) goes further into the problem.

I have created a pull request in order to illustrate a fix. It adds an optional arguments that allows you to supply custom tags to the yaml parser.

So please let me know if you have a better solution or adjustments I should make before merging.

**Comment by RodrigoGonzalez** [comment]
Implemented in https://github.com/RodrigoGonzalez/check-mkdocs/pull/40
